name: Rust Test and Release
on:
  push:
    tags: ['v*']

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
jobs:
  MainTest:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: linux-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            suffix: macos-aarch64

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{matrix.target}}
      - uses: Swatinem/rust-cache@v2
      - name: Cargo Build
        id: build
        run: cargo build --release --target ${{matrix.target}}
      - name: Disseminate Status to webhook
        run: >
          curl -X POST -H 'Content-type: application/json'
          --data '{"text":"ðŸ—ï¸ Build ran: ${{steps.build.outcome}}"}'
          ${{secrets.WEBHOOK_URL}}
      - name: Cargo Test
        id: test
        run: cargo test --verbose
      - name: Disseminate Status to webhook
        run: >
          curl -X POST -H 'Content-type: application/json'
          --data '{"text":"ðŸ§ª Test ran: ${{steps.test.outcome}}"}'
          ${{secrets.WEBHOOK_URL}}
      - name: Prep Binary
        shell: bash
        run: |
          mkdir dist
          cp target/${{matrix.target}}/release/weather_cli dist/weather_cli-${{matrix.suffix}}
          strip dist/weather_cli-${{matrix.suffix}}

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files:
            dist/*
      - name: Disseminate Status to webhook
        run: >
          curl -X POST -H 'Content-type: application/json'
          --data '{"text":"ðŸ”‚ Release for ${{matrix.suffix}} ran: ${{steps.release.outcome}}"}'
          ${{secrets.WEBHOOK_URL}}
